p1 = input().split()
cod_p1 = int(p1[0])
num_p1 = int(p1[1])
valor_p1 = float(p1[2])
p2 = input().split()
cod_p2 = int(p2[0])
num_p2 = int(p2[1])
valor_p2 = float(p2[2])
total = (num_p1 * valor_p1) + (num_p2 * valor_p2)
print ("VALOR A PAGAR: R$ %.2f" %total)